#!/bin/bash

set -e -x

release_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

BUILT_RESOURCE=$PWD/built-resource

DOCKER_VERSION=$(cat docker/config/docker-version | sed 's/^v//')

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd $(dirname $0)/../..

go install github.com/concourse/docker-image-resource/vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p -skip "DockerImageResource"

go build -o ./assets/check ./cmd/check/
go build -o ./assets/print-metadata ./cmd/print-metadata/

curl -sSL -O "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz"
tar xzvf "docker-${DOCKER_VERSION}.tgz"

go build -o ./ecr-login github.com/concourse/docker-image-resource/vendor/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cmd

cp -a ./* ${BUILT_RESOURCE}/

cp "${workspace_dir}/${DOCKERFILE_DIR}/Dockerfile" ${BUILT_RESOURCE}/
